[package]
name = "jsonschema_transpiler"
version = "0.1.0"
authors = ["Anthony Miyaguchi <amiyaguchi@mozilla.com>"]
edition = "2018"

[lib]
name = "jst"

[dependencies]
clap = "~2.32"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
