[package]
name = "jsonschema_transpiler"
version = "0.1.0"
authors = ["Anthony Miyaguchi <amiyaguchi@mozilla.com>"]
edition = "2018"

[lib]
name = "converter"

[dependencies]
clap = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"

[build-dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"